import Navbar from "@/components/Nav/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Provider } from "@/components/ui/provider";
import { Box, Flex } from "@chakra-ui/react";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html suppressHydrationWarning lang="en">
			<body className={`${dmSans.className}`}>
				<Provider>
					<Box>
						<Navbar />
						<Flex flexDir="row" flex={"auto"}>
							<Sidebar />
							<Box
								w={{ base: "100%", md: "calc(100% - 350px)" }}
								minH={"calc(100vh - 80px)"}
								bg={"teal"}
								pt={10}
								px={{ base: 5, md: 20 }}
							>
								{children}
							</Box>
						</Flex>
					</Box>
				</Provider>
			</body>
		</html>
	);
}
